### PR TITLE
Support unprotected gnupg keys

### PR DESCRIPTION
**Pull request by gaellalire**
#489

### CODE REVIEW

**Comment by bcgit** [comment]
Can you provide any test data?

**Comment by gaellalire** [comment]
You mean writing unit test or just generating a gpg key with no passphrase ?

**Comment by bcgit** [comment]
I just need some sample keys without the passphrase.

**Comment by gaellalire** [comment]
[gnupg.zip](https://github.com/bcgit/bc-java/files/3060916/gnupg.zip)

**Comment by bcgit** [comment]
Merged with minor changes. Thanks!

**Pull request closed without merging**
