### PR TITLE
Allow roundtripping OpenPGP packet format

### PR DESCRIPTION
**Pull request by vanitasvitae**
The OpenPGP protocol defines different formats to encode packet lengths.
BC supports reading and writing both packet format types, though it is not always clear, how to chose, which format to use.

This PR improves the status quo by defining an enum `PacketFormat` consisting of 3 options:
* `LEGACY`: Always encode packets using the old legacy packet format
* `CURRENT`: Always encode packets using the current (new) packet format
* `ROUNDTRIP`: Encode packets that were read from an `InputStream` the same way they were originally encoded.

Further, packets now contain a new flag remembering the packet format they were originally encoded in.
This, and the fact that there is a new `BCPGOutputStream` constructor allowing the user to chose which format encoding strategy to use allows to round-trip packet streams without changing the packet format.

`getEncoded()` now round-trips the original packet format, but the user can decide, in which format they want to retrieve the packet encoding by calling e.g. `getEncoded(PacketFormat.LEGACY)`.

The changes were introduced in a backwards compatible way and the tests still run successful.

### CODE REVIEW

**Comment by dghgit** [comment]
I'm seeing a failure in OnePassSignaturePacketTest, would you take a look? Getting:

Expected: 
00000000  90 0d 03 00 08 01 00 00  00 00 00 00 00 7b 00 

Got: 
00000000  c4 0d 03 00 08 01 00 00  00 00 00 00 00 7b 00 

Looks like something may not be fully round-tripping.

Thanks.

**Comment by vanitasvitae** [comment]
Ah, probably because you locally applied this PR over https://github.com/bcgit/bc-java/pull/1634
I did not yet update this PR based on that patch :D

Will update :)

**Comment by vanitasvitae** [comment]
Rebased and fixed.

**Comment by dghgit** [comment]
Thanks, now passes. Merged!

**Pull request closed without merging**
