### PR TITLE
Add non-blocking API to TlsProtocol

### PR DESCRIPTION
**Pull request by rdicroce**
This PR supersedes #68. It's not a split of that PR, it's a complete rewrite that has a cleaner API and less invasive changes. The TLS-SRP changes will be done as part of a separate PR, as requested.

### CODE REVIEW

**Comment by timw** [comment]
This is another of those changes where a 1.5/6/7/8+ source tree + build to newer JVM features could be useful (java.nio dependencies clash with the desire to keep BC building/running on JDK 1.1ish).
It looks like this PR could be modified to remove the java.nio deps though...

**Comment by rdicroce** [comment]
I'm not sure what the rationale is for continuing to support JDKs < 5. As far as I know, Oracle doesn't offer any kind of support for those versions. 5 and 6 are no longer receiving public updates, and 7 will be joining them in a couple months. The only other JVM that I've heard of people using is IBM's; it looks like they're still supporting 1.4.

Bottom line: if you're using an older than dirt JVM, you should really consider upgrading. A lot of other Java libraries are ditching support for older versions of Java anyway. 6 seems to have become the baseline, and some even require 7 (Apache Lucene comes to mind).

**Comment by timw** [comment]
This topic pops up semi-regularly on the BC dev list, but tl;dr: BC is used a lot in embedded systems, J2ME etc. that are fairly frozen in time wrt Java version, so portability is valued.

**Comment by peterdettman** [comment]
We're going to defer this to the next release again, sorry (currently putting 1.52 together). I'm sympathetic to the JDK constraints, believe me. As @timw alludes, a path forward is to externalize anything JDK (or IO-lib) dependent via an API, and have a separate module/project supply an implementation.

**Comment by rdicroce** [comment]
Creating an API might be a good idea anyway, now that I'm thinking about it. It could simplify integration with other libraries like Netty, which has its own ByteBuf class. I might explore that if I have some time.

**Comment by rdicroce** [comment]
I've changed the PR so it no longer uses ByteBuffer, only byte arrays now. Also rebased it on top of current master. And added some additional testing, which revealed the original PR had a serious bug when partial records arrived. That issue is fixed now.

**Comment by mezz** [comment]
Any news now that 1.52 is released?

**Comment by rivervilla** [comment]
Any chance non-blocking TLS and/or DTLS will be in 1.53?

**Comment by peterdettman** [comment]
Honestly, I had missed the fact that @rdicroce had updated this PR. My apologies for that. We are busy with the FIPS work just now, but I will find some time to review this and see if we can get it into 1.53.

**Comment by ivelin** [comment]
@peterdettman Can you please share an update on timeframe for NIO?

**Comment by peterdettman** [comment]
Merged. Thanks @rdicroce for the patch, particularly for reworking it to accommodate our Java version constraints.

**Comment by rdicroce** [comment]
@peterdettman It looks like this did not make it into 1.53, so I assume it will be in 1.54 then? Also it looks like the merge has not been pushed to GitHub yet.

**Comment by rivervilla** [comment]
I'll look at changes but this is true non-blocking meaning partial records will not cause problems. I'm also in need of a negotiation callback so that user may allow client cert privacy through rehandshake after connection is protected.  Yes different issue.  Thanks.

**Comment by peterdettman** [comment]
No, it didn't make it into 1.53. It'll be in the next beta build of 1.54 which shouldn't be too long. It also takes a little while for our git commits to mirror back to github (maybe just check back tomorrow).

**Comment by bcgit** [comment]
This is now up on http://www.bouncycastle.org/betas (154b03 or later). The code changes will appear in the main branch here shortly - the github mirror has been updated, it just needs to sync up.

**Comment by sscheck** [comment]
What are the relevant classes for non-blocking mode? I don't see any TlsServer or DatagramTransport implementations that obviously indicate non-blocking operation.

**Comment by rdicroce** [comment]
For TLS, the relevant methods are on TlsServer/ClientProtocol. I didn't do any work on DTLS, and AFAICT the release notes for 1.54 are incorrect in saying that a non-blocking API was added for DTLS.

**Pull request closed without merging**
