### PR TITLE
Add KeyAgreementNoPaddingSpi that implements old, unpadded bigIntToBytes

### PR DESCRIPTION
**Pull request by DmitryLitvintsev**
to support clients that use unpadded DH_comute_key (openssl). Add
"DHNP" KeyAgreement algorithm to invoke this code path

### CODE REVIEW

**Comment by bcgit** [comment]
Try generateSecret("TlsPremasterSecret") - I think it will do what you want correctly now, rather than having to add another service.

**Comment by DmitryLitvintsev** [comment]
Hi, 
Thank you for suggestion! I think I will need some guidance. My current server side code is 
```KeyAgreement _keyAgreement = KeyAgreement.getInstance("DH", "BC");
    ....
   byte [] iv = new byte[16];
   Arrays.fill(iv, (byte)0);
   final byte[] sharedSecret = _keyAgreement.generateSecret();
   SecretKey sessionKey = new SecretKeySpec(sharedSecret,
                                                0,
                                                16,
                                                "AES");
   IvParameterSpec paramSpec = new IvParameterSpec(iv);
   Cipher cipher = Cipher.getInstance(""AES/CBC/PKCS5Padding","BC");
   cipher.init(Cipher.DECRYPT_MODE, sessionKey, paramSpec);
   byte[] decrypted = cipher.doFinal(encrypted); // encrypted is byte array off the wire
```

`generateSecret.generateSecret("TlsPremasterSecret")` returns `SecretKey` , not a byte array. Passing `_keyAgreement.generateSecret("TlsPremasterSecret").getEncoded()` to `SecretKeySpec` does not help.

**Comment by bcgit** [comment]
You might need to include an Arrays.copyOfRange(_keyAgreement.generateSecret("TlsPremasterSecret").getEncoded(), 0, 16) - the return value is the full agreement value, converted to a byte array, or is there some other issue?

**Comment by DmitryLitvintsev** [comment]
Ah, the issue is that if I do this
```
SecretKey sessionKey = new SecretKeySpec(_keyAgreement.
                                                                          generateSecret("TlsPremasterSecret").
                                                                          getEncoded(),
                                                                          0,
                                                                          16);
....
```
I get the same error `pad block corrupted` in 0.5% of tries, that I get by using original code that a quoted in my previous comment.  (and also there is an issue https://github.com/bcgit/bc-java/issues/413). Using suggested `Arrays.copyOfRange` does not help too.

**Comment by DmitryLitvintsev** [comment]
OK, I figured out what the issue might be here. We are discussing code on the master, whereas my server runs against BC 1.50

As far as I could see there is no handling of " TlsPremasterSecret" in BC 1.50. 
(tag 1rv50). Interesting that it just did not fail w/ NoSuchAlgorithmException.

**Comment by DmitryLitvintsev** [comment]
Indeed. So, I added handling of "TlsPremasterSecret" in `KeyAgreementSpi.java` on  r1rv50
(I had to add `trimZeroes` function to `KeyAgreementSpi` to handle "TlsPremasterSecret" alrgorithm)
and it seems to *work fine* with the workaround you have suggested (use `generateSecret("TlsPremasterSecret")`). 

I have not tried master as we can't easily adapt to it, but all indication is that it will work. 

Residual question: it is possible to add this fix to existing supported versions? 

Thank you, 
Dmitry

**Comment by bcgit** [comment]
That's a bit unexpected, what key agreement algorithm are you using?

**Comment by DmitryLitvintsev** [comment]
Well, on  r1rv50 : 

```
[litvinse@orbis bc-java]$ git checkout r1rv50
Previous HEAD position was ef676b6f7... update
HEAD is now at f6f530b18... updates
[litvinse@orbis bc-java]$ find prov/ -name '*.java' -exec egrep -H 'TlsPremasterSecret' {} \; 
[litvinse@orbis bc-java]$  
```
(Nothing about TlsPremasterSecret). I am using:

```
_keyAgreement = KeyAgreement.getInstance("DH", "BC");
```

**Comment by bcgit** [comment]
Try 1.59

**Comment by DmitryLitvintsev** [comment]
Thank you. I believe I can close this pull request. I have found a working solution:
 a patched `KeyAgreementSpi` in 1.50 + `generateSecret("TlsPremasterSecret")`. We will make our custom BC jar and will be using it until we can upgrade to newer version.

**Comment by DmitryLitvintsev** [comment]
I am re-opening this pull request only to solicit more guidance/help.. 

I have explored switching our application to BC 1.60. 

It fails when trying to handshake w/ another application (xrootd server written in C++). 

```
org.bouncycastle.jcajce.provider.asymmetric.util.ExtendedInvalidKeySpecException: unsafe p value so small specific l required
       at org.bouncycastle.jcajce.provider.asymmetric.dh.KeyFactorySpi.engineGeneratePublic(Unknown Source)
       at java.security.KeyFactory.generatePublic(KeyFactory.java:328)
       at org.dcache.xrootd.plugins.authn.gsi.DHSession.finaliseKeyAgreement(DHSession.java:177)
       ...
```

It is true that xrootd application sends us a short P. It is possible to by-pass this somehow? (we can't easily change the other application). 

I see that a proper constructor exists:

```
public DHParameters(
        BigInteger  p,
        BigInteger  g,
        BigInteger  q,
        int         m,
        int         l)
    {
        this(p, g, q, m, l, null, null);
    }
```

But I don't see a way of invoking it. 
(I may be completely on the wrong track here so any advice is greatly appreciated)

**Comment by bcgit** [comment]
For future reference it's better to open a new issue.This got missed.

I've add "org.bouncycastle.asn1.allow_p_value" if set to true the test is not carried out.

**Pull request closed without merging**
