### PR TITLE
Bugfix and improvement of CMP messages

### PR DESCRIPTION
**Pull request by xipki**

### CODE REVIEW

**Comment by bcgit** [comment]
Thanks for the patch. I've merged most of this, with a minor revision to preserve the original API. I've added a getCertReqIdValues() to PollReqContent which just returns an array of CertReqId values.

**Comment by xipki** [comment]
Thanks for the quick fix.
BTW, please merge all my entries in http://bouncycastle.org/contributors.html. You can use "Lijun Liao <https://github.com/xipki>" as my identifier.

**Comment by bcgit** [comment]
Are you also "lijun.liao at rub.de" and "jun.liao at gmail.com"?

**Comment by xipki** [comment]
Yes. It is me.

**Pull request closed without merging**
