### PR TITLE
BCRSAPrivateKey.java: Serialize algorithmIdentifier

### LINKED ISSUE #682: RSASSA-PSS change breaks BCRSAPrivateKey Java serialization
It appears that a309b4f573eb4a1314649480541cecf2da11827a broke Java serialization (for both RSA and RSASSA-PSS keys). This simple test case proves it:

```diff
diff --git a/prov/src/test/java/org/bouncycastle/jce/provider/test/RSATest.java b/prov/src/test/java/org/bouncycastle/jce/provider/test/RSATest.java
index 58043eb0f..9cef962ad 100644
--- a/prov/src/test/java/org/bouncycastle/jce/provider/test/RSATest.java
+++ b/prov/src/test/java/org/bouncycastle/jce/provider/test/RSATest.java
@@ -753,6 +753,10 @@ private void testPSSKeys()
 
         isTrue("RSASSA-PSS".equals(privateKey.getAlgorithm()));
 
+        privateKey = (PrivateKey)serializeDeserialize(kp.getPrivate());
+
+        isTrue("RSASSA-PSS".equals(privateKey.getAlgorithm()));
+
         SubjectPublicKeyInfo subKey = SubjectPublicKeyInfo.getInstance(publicKey.getEncoded());
 
         isTrue(null == subKey.getAlgorithm().getParameters());
```

Results in:
```
> Task :prov:RSATest.main()
java.lang.NullPointerException
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.BCRSAPrivateKey.getAlgorithm(BCRSAPrivateKey.java:79)
	at org.bouncycastle.jce.provider.test.RSATest.testPSSKeys(RSATest.java:758)
	at org.bouncycastle.jce.provider.test.RSATest.performTest(RSATest.java:721)
	at org.bouncycastle.util.test.SimpleTest.perform(SimpleTest.java:180)
	at org.bouncycastle.util.test.SimpleTest.runTest(SimpleTest.java:203)
	at org.bouncycastle.util.test.SimpleTest.runTest(SimpleTest.java:198)
	at org.bouncycastle.jce.provider.test.RSATest.main(RSATest.java:990)
RSATest: Exception: java.lang.NullPointerException
```

### PR DESCRIPTION
**Pull request by lipnitsk**
Fixes #682 

Fixes regression introduced in a309b4f573eb4a1314649480541cecf2da11827a

### CODE REVIEW

**Comment by bcgit** [comment]
Thanks for the patch, and especially the test. Merged!

**Comment by lipnitsk** [comment]
Thanks! Would there be a hotfix release soon with this regression fix?

**Comment by peterdettman** [comment]
We do produce betas regularly (at https://downloads.bouncycastle.org/betas/), expect a 166b02 within the next few days.

**Comment by lipnitsk** [comment]
Okay, so for production use we are stuck with workarounds or 1.64 until 1.66 is released in a few months?

**Comment by bcgit** [comment]
Planing to do a patch release for the provider only, please check 166b03 - there was still an issue with the serialization in 166b02

**Pull request closed without merging**
