### PR TITLE
Enable nohttp check during the build

### PR DESCRIPTION
**Pull request by artem-smotrakov**
HTTP is a plaintext protocol which means that someone may be able to eavesdrop the data. To prevent this, HTTPS should be used whenever possible. However, maintaining using `https://` in all URLs may be difficult. The `nohttp` tool can help here. The tool scans all the files in a repository and reports where `http://` is used.

Here is a list of main updates:

- Updated `build.gradle` to call `nohttp` during the build.
- Updated `http://` to `https://` in URLs.
- Added an exclude list.

Sorry for many updated files. All the findings had to be fixed or suppressed.

Here are some info about the tool:

- https://github.com/spring-io/nohttp
- https://spring.io/blog/2019/06/10/announcing-nohttp

### CODE REVIEW

**Comment by dghgit** [comment]
I'm working through this one, just have to be a little careful in case there is something which is actually supposed to be http.

**Comment by dghgit** [comment]
Thanks for the patch, I think this has now been done in all the places it is appropriate to do so.

**Comment by artem-smotrakov** [comment]
> Thanks for the patch, I think this has now been done in all the places it is appropriate to do so.

@dghgit The purpose of this tool is to prevent unsafe http:// link from appearing again.

**Review by dghgit — COMMENTED** [review]
updated to use 0.0.8, thanks for providing the config files as well. It should appear on github in the next day.

**Pull request closed without merging**
