### PR TITLE
Update DefaultSignatureAlgorithmIdentifierFinder.java

### PR DESCRIPTION
**Pull request by bschuette**
Typo: SHA224WITHCVC-ECDSA not SHA224WITHPCVC-ECDSA

### CODE REVIEW

**Comment by bcgit** [comment]
Done.

**Comment by bschuette** [comment]
This is still not fixed in the current release 1.55, please merge this commit.

**Comment by bcgit** [comment]
It was fixed in June. You might want to check your class path.

**Comment by bschuette** [comment]
https://github.com/bcgit/bc-java/blob/r1rv55/pkix/src/main/java/org/bouncycastle/operator/DefaultAlgorithmNameFinder.java  

also on master it's still

**Comment by bcgit** [comment]
Oh dear. I've fixed it - it's not the class this issue was raised against though.

**Comment by bschuette** [comment]
Yep, sorry for the confusion, just figured out it was another file. Should have fixed both in the first place.

**Pull request closed without merging**
