### PR TITLE
Fix EdEc key conversions from Sun implementations fixes #862

### LINKED ISSUE #862: X25519PublicKeyParameters.<init> exception
Using 1.68, OpenJdk 13, apache httpClient v 4.5.12

I see the following exception **randomly** (so sometimes happens sometimes not, same code, same JDK, just the time is different) :

It caused here:
https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/params/X25519PublicKeyParameters.java

```
public X25519PublicKeyParameters(byte[] buf, int off)
    {
        super(false);

        System.arraycopy(buf, off, data, 0, KEY_SIZE);   //here the exception occurs
    }
```

Exception:
```
javax.net.ssl.SSLException: arraycopy: last source index 32 out of bounds for byte[31]
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1652)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:443)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:191)
        at org.apache.http.impl.conn.BasicHttpClientConnectionManager.upgrade(BasicHttpClientConnectionManager.java:325)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:428)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at...

        Caused by:
        java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 32 out of bounds for byte[31]
            at java.base/java.lang.System.arraycopy(Native Method)
            at org.bouncycastle.crypto.params.X25519PublicKeyParameters.<init>(Unknown Source)
            at org.bouncycastle.jcajce.provider.asymmetric.edec.KeyAgreementSpi.engineDoPhase(KeyAgreementSpi.java:163)
            at java.base/javax.crypto.KeyAgreement.doPhase(KeyAgreement.java:579)
            at java.base/sun.security.ssl.KAKeyDerivation.t13DeriveKey(KAKeyDerivation.java:104)
            at java.base/sun.security.ssl.KAKeyDerivation.deriveKey(KAKeyDerivation.java:63)
            at java.base/sun.security.ssl.ServerHello$T13ServerHelloConsumer.consume(ServerHello.java:1290)
            at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.onServerHello(ServerHello.java:1005)
            at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.consume(ServerHello.java:893)
            at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
            at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
            at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
            at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
            at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
            at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1460)
            at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1368)
            at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437)
            ... 11 more
```

Could you pls investigate what can cause this?

### PR DESCRIPTION
**Pull request by tonywasher**

### CODE REVIEW

**Comment by peterdettman** [comment]
Merged with significant followup work. Thanks, Tony.

**Comment by dkocher** [comment]
Why are the referenced issues not closed?

**Comment by SalusaSecondus** [comment]
Also, why do we not see the fix in the `master` branch yet?

**Comment by peterdettman** [comment]
There's now a beta (1.69b01) up at https://downloads.bouncycastle.org/betas/ that includes this fix.

@SalusaSecondus This repo is a mirror of our private repo so updates only appear here once we sync them. Usually that happens regularly, but sometimes not so much. In regard to `equalsIgnoreCase`, I believe these names have already been canonicalized - naming variations are dealt with at the provider registry level.

**Pull request closed without merging**
