### PR TITLE
Change == to .equals()

### PR DESCRIPTION
**Pull request by bmsiegel**
https://github.com/bcgit/bc-java/issues/1284

### CODE REVIEW

**Comment by divyansh-gupta** [comment]
I also need this change, thank you!

**Comment by KyleBS** [comment]
I also need this change, thank you!

**Comment by dghgit** [comment]
Merged. Thanks!

**Comment by bmsiegel** [comment]
https://github.com/bcgit/bc-java/commit/7105ce7a992fb5241b2b78b104b3275422039b02

This introduces an NPE risk, while reordering as I have here is safer. Mind changing it to this?

**Pull request closed without merging**
