### PR TITLE
Fixed name constraint comparison

### PR DESCRIPTION
**Pull request by koh-osug**
The `PKIXNameConstraintValidator` was most likely not merged correctly, it is now using again the old behavior where all subtrees and DNs must be identical. This is not according to https://tools.ietf.org/html/rfc5280#section-7.1

This is related to this pull request:

https://github.com/bcgit/bc-java/pull/496

### CODE REVIEW

**Comment by koh-osug** [comment]
Any updates here?

**Comment by bcgit** [comment]
I'm not so sure about this one, this was something that actually got fixed after the merge. Working backwards through the DN would be correct if it was an IETF string representation, but the code actually uses the encoding. Do you have an example this fails for? It would help if I had a clearer idea of what the problems, if any, there were. Thanks.

**Comment by koh-osug** [comment]
Yes. I attach an example from the SGP.26 specification which is for the SGP.22 specification used as standard for all eSIM provision systems (https://www.gsma.com/newsroom/resources/sgp-22-v2-2-technical-specification/):

This is the signing certificate of the EUM (eUICC manufacturer = SIM manufacturer):
```
openssl x509 -in CERT_EUM_ECDSA_NIST.txt -text
Certificate:
    Data:
        Version: 3 (0x2)
        ...
        X509v3 extensions:
       ...
            X509v3 Name Constraints: critical
                Permitted:
                  DirName: O = RSP Test EUM, serialNumber = 89049032
   ....
```

Here the eUICC certificate signed by the EUM:

```
 openssl x509 -in CERT_EUICC_ECDSA_NIST.txt -text
Certificate:
    Data:
        Version: 3 (0x2)
       ...
        Subject: C=DE, O=RSP Test EUM/serialNumber=89049032123451234512345678901235, CN=Test eUICC
 ...
```

Here the name constraint of the EUM defines that any signed certificate must have a subject coming from the organisation `O = RSP Test EUM` and starting with a serial number of `serialNumber = 89049032` (support for serial numbers where already with a previous patch).

The eUICC certificate fulfills this requirement by coming from this organisation and is starting with the serial number. In addition the eUICC certificate defines other subject fields, here the country `C=DE` and a common name `CN=Test eUICC`. This is valid because the name constraint is only restricting the permitted subject names, not additional ones. The current BC implementation fails here. I quote here a different statement from RFC 5280  https://tools.ietf.org/html/rfc5280#section-4.2.1.10:

> Restrictions apply only when the
   specified name form is present.  If no name of the type is in the
   certificate, the certificate is acceptable.

The specified name forms are here the `O` and the `serialNumber`, not the `C` and `CN` why the name constraint check must not fail.

[CERT_CI_ECDSA_NIST.txt](https://github.com/bcgit/bc-java/files/3534182/CERT_CI_ECDSA_NIST.txt)

[CERT_EUM_ECDSA_NIST.txt](https://github.com/bcgit/bc-java/files/3534184/CERT_EUM_ECDSA_NIST.txt)

[CERT_EUICC_ECDSA_NIST.txt](https://github.com/bcgit/bc-java/files/3534188/CERT_EUICC_ECDSA_NIST.txt)

**Comment by bcgit** [comment]
Okay, I think this is now "fixed" (by that I mean the above works and so do the NIST tests). Let me know how you go with it. The fixed version is up on https://www.bouncycastle.org/betas

**Comment by koh-osug** [comment]
I have verified the beta and this works. Thanks.

**Comment by bcgit** [comment]
Thanks.

**Pull request closed without merging**
