### PR TITLE
Add method to join two copies of a public key

### PR DESCRIPTION
**Pull request by vanitasvitae**
This method comes in handy, whenever a public key needs to be merged
with another copy of the same key, e.g. when consuming updates from
a key server.

This implementation does not do any verification on signatures and
blindly merges the data together.
Verification is left to the implementation, just like in other places
of BCs PGP implementation.

I added two flags which modify the methods behavior:
* `joinTrustPackets` controls whether changed trust packets from `copy` will be adopted in the resulting merged key
* `allowSubkeySigsOnNonSubkey` controls whether in case of a non-subkey `key`, subkey signatures on `copy` should be accepted into the resulting merged key, which would transform it into a subkey, which might cause issues with BCs implementation (e.g. primary keys must not have subkey signatures currently, although the standard would not forbid it).

Let me know what you think :)

### CODE REVIEW

**Comment by vanitasvitae** [comment]
I would especially be interested in whether there is a better way to check for signature equality than `Arrays.areEqual(sig1.encode(), sig2.encode())`.

**Comment by vanitasvitae** [comment]
I changed signature comparison to comparing the actual cryptographic signature encoding. This should deal with different encodings of the PGPSignature packet I believe.

Furthermore I added a method to merge the unhashed subpacket areas of signatures.

**Comment by dghgit** [comment]
It sounds a little complicated and a little risky... I'd probably be verifying prior to merging. Would I be right if I was to think that this is really about not having things duplicated?

**Comment by vanitasvitae** [comment]
I added some test vectors which were kindly provided by Sequoia-PGP.
The code is passing those tests happily :)

**Comment by vanitasvitae** [comment]
> Would I be right if I was to think that this is really about not having things duplicated?

Yes. User-IDs, Keys and Signatures from both copies of the certificate are copied together into the resulting key.

**Comment by vanitasvitae** [comment]
Is there anything I can do to help this PR get merged? :)

**Comment by dghgit** [comment]
I've started looking at it. Sorry things have been a bit crazy of late.

**Comment by dghgit** [comment]
Merged with a minor change. I dropped the KeyFingerPrintCalculator parameter. Should appear on github shortly.

**Comment by dghgit** [comment]
Now up at https://www.bouncycastle.org/betas 171b18 or later.

**Comment by vanitasvitae** [comment]
Awesome, thanks for taking care of this :)

**Pull request closed without merging**
