### PR TITLE
for #528 Basic AuthEnveloped Content Encryptor, inlcuding attributes. 

### PR DESCRIPTION
**Pull request by MadMud**
Hi, creating a PR for now. 
We might want to collect a bit more wore before we merge, but I wanted to easily point to my commit.

Basic AuthEnveloped Content Encryptor, inlcuding attributes. 
For now AES/GCM only, others can easily be added.

### CODE REVIEW

**Comment by bcgit** [comment]
Just looking at this one now... there will be a couple of (smallish) changes...

**Comment by MadMud** [comment]
Hi,
Sure thing! I have since changed the auth attributes handover to accommodate the authenveloped CMS generators. 
However these changes contain a bit of refactoring of the ASN.1 pojos and CMS parsers (authenveloped extends enveloped). 
I realize this is a bit of design change, so would you like me to put it in this PR or into a new one?
Cheers,
Matthias

**Comment by bcgit** [comment]
I've synced up the latest. It should appear on github shortly.

**Comment by bcgit** [comment]
Erm, everyone's noticed the work that was done on CMSAuthEnvelopedDataGenerator and CMSAuthEnvelopedData a couple of weeks ago haven't they?

**Comment by MadMud** [comment]
On my mobile rightniw,but are referring to the merger of my pull request #528 ? That is in direct lint to what is in my fork now.
 At the time we wanted a way of producing authenveloped with authed attributes, so I did that first

**Comment by MadMud** [comment]
Ok merge is done. Please have a look and comment on wether or not we want to proceed using Authenveloped extends enveloped

**Comment by bcgit** [comment]
No, I wouldn't have AuthEnveloped extend Enveloped, ASN.1 is a lot of things, but OO it isn't. The two structures really different.

**Comment by MadMud** [comment]
Hmm,
I generally agree, but in this case all of the properties in enveloped are in auth enveloped. Also in the same order. Have you looked at the code?
Anyway,the alternative is to copy all the code from enveloped an either all generators or extract an interface. 
Cheers,
Mad

**Comment by dghgit** [comment]
Thanks for suggestions, marking this as closed as I think this has finally iterated to something workable. The most difficult thing to deal with properly was the manner in the mac gets treated. I think the current approach will work for streaming as well, but that's something we'll need to look at later.

**Pull request closed without merging**
