### PR TITLE
Initial implementation of GOST 3412 2015

### PR DESCRIPTION
**Pull request by MikeSafonov**
This pull request contains initial implementation of GOST 3412 2015 (aka "Kuznyechik") [RFC 7801](https://tools.ietf.org/html/rfc7801), [GOST 3412](https://www.tc26.ru/standard/gost/GOST_R_3412-2015.pdf) (**_org.bouncycastle.jcajce.provider.symmetric.GOST3412_2015_** and **_org.bouncycastle.crypto.engines.GOST3412_2015Engine_**).

Implemented modes ( [GOST 3413](https://www.tc26.ru/standard/gost/GOST_R_3413-2015.pdf) ):

- CMAC (OMAC1)
- ECB
- CTR (**_org.bouncycastle.crypto.modes.G3412CTRBlockCipher_**) 
- CFB (**_org.bouncycastle.crypto.modes.G3412CFBBlockCipher_** and **_org.bouncycastle.crypto.modes.G3412CFBStreamBlockCipher_**) 
- OFB (**_org.bouncycastle.crypto.modes.G3412OFBBlockCipher_**)
- CBC (**_org.bouncycastle.crypto.modes.G3412CBCBlockCipher_**)

Tests: **_org.bouncycastle.crypto.test.GOST3412Test_** and **_org.bouncycastle.crypto.test.GOST3412MacTest_**

### CODE REVIEW

**Comment by MikeSafonov** [comment]
Hello
What about this pull request?

**Comment by bcgit** [comment]
Sorry, next on my list. There's been rather a lot going on at the moment...

**Comment by bcgit** [comment]
Merged with some changes.

I've removed the special parameters class as it appears S and M are related to block size and the IV length with S being the usual, say 8 for CFB8. M is different in that it makes it possible for the IV to be more than one block in length.

I've added the basic implementation to the provider as well. It would be good to get some more test vectors (especially for things like CFB8) and also are there any object identifiers for these? I had a look around but have not found anything so far. Should appear on github shortly.

**Comment by MikeSafonov** [comment]
Unfortunately I also did not find any OID

**Comment by bcgit** [comment]
Don't worry, I'm sure one will show up... Anything that can be done to expand the test vector set would help as well though.

**Comment by bcgit** [comment]
Closing off for the moment. When OIDs show up we will open another issue.

**Pull request merged**
