### PR TITLE
Fix wraparound counter bug which leaks plaintext and auth key

### PR DESCRIPTION
**Pull request by andybons**
If the plaintext/ciphertext length is larger than 2^36 - 32 bytes, the counter is wrapped and it leaks the plaintext and authentication key.

This issue and fix was originally authored by Quan Nguyen

### CODE REVIEW

**Comment by peterdettman** [comment]
I believe this limitation is already enforced in the current code, except by counting blocks. See the `GCMBlockCipher.blocksRemaining` field and its usage. Could you please re-examine on that basis, and let us know if you think that insufficient/incorrect for some reason.

**Comment by bcgit** [comment]
I've a feeling this might be based on an earlier version of BC, although if there is an error with blocksRemaining we would like to hear about it.

**Comment by andybons** [comment]
This is indeed based on a change made to 1.52. I’ve asked my colleagues with more domain expertise (the ones who actually wrote the patches) to help with these PRs.

**Comment by bcgit** [comment]
Closed as appears to be already dealt with.

**Pull request closed without merging**
